### ISSUE TITLE
`axum::Router.layer` complaining about `tower_http::cors::CorsLayer`, fixed with tower downgrade

### ISSUE THREAD

**Issue by databasedav** [tower-rs/tower-http#444]
### Version

0.5.0

### Platform

Ubuntu 23.04

### Repro
```toml
[package]
name = "tower_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
serde = { version = "1.0.193", features = ["derive"] }
tower-http = { version = "0.5.0", features = ["cors"] }
```
```rust
use axum::{self, response::IntoResponse};
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize)]
struct Payload;

async fn endpoint(axum::Json(payload): axum::Json<Payload>) -> impl axum::response::IntoResponse {
    axum::http::StatusCode::OK.into_response()
}

fn make_app() -> axum::Router {
    axum::Router::new()
    .route("/endpoint", axum::routing::post(endpoint))
    .layer(tower_http::cors::CorsLayer::permissive())
}

fn main() {
    make_app();
}
```
```rust
error[E0277]: the trait bound `Cors<Route<_>>: tower_service::Service<axum::http::Request<_>>` is not satisfied
   --> src/main.rs:14:12
    |
14  |     .layer(tower_http::cors::CorsLayer::permissive())
    |      ----- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tower_service::Service<axum::http::Request<_>>` is not implemented for `Cors<Route<_>>`
    |      |
    |      required by a bound introduced by this call
    |
    = help: the trait `tower_service::Service<http::request::Request<ReqBody>>` is implemented for `Cors<S>`
note: required by a bound in `Router::<S, B>::layer`
   --> /home/avi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.6.20/src/routing/mod.rs:236:21
    |
233 |     pub fn layer<L, NewReqBody>(self, layer: L) -> Router<S, NewReqBody>
    |            ----- required by a bound in this associated function
...
236 |         L::Service: Service<Request<NewReqBody>> + Clone + Send + 'static,
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Router::<S, B>::layer`


```
running `cargo add tower-http@0.4.4` fixes the issue, i also tried downgrading axum but the issue persisted
