### ISSUE TITLE
not all trait items implemented, missing: `on_failure`

### ISSUE THREAD

**Issue by fate-zx** [tower-rs/tower-http#495]
error[E0046]: not all trait items implemented, missing: `on_failure`
  --> \.cargo\registry\src\index.crates.io-6f17d22bba15001f\tower-http-0.5.2\src\trace\on_response.rs:35:1
   |
27 | /     fn on_failure(
28 | |         &mut self,
29 | |         error: &hyper::Error,
30 | |         latency: std::time::Duration,
31 | |         span: &Span,
32 | |     );
   | |______- `on_failure` from trait
...
35 |   impl<B> OnResponse<B> for () {
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `on_failure` in implementation

tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5.2", features = ["trace"] }

**Comment by jplatte** [comment]
I put

```toml
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5.2", features = ["trace"] }
```

in a `Cargo.toml` and checked whether it compiles. It does, so I'll assume that this issue is either invalid, or was already fixed.
